### ISSUE TITLE
Exception in thread "main" overflowdb.traversal.filter.StringPropertyFilter$InvalidRegexException: invalid regular expression

### ISSUE THREAD

**Issue by almaz045** [AppThreat/atom#154]
I've tried to test depscan on https://github.com/grpc/grpc by next command:

> atom reachables -o app.atom -s reachables.json -l c .
p.s. bom.json is exist

And got next error:

```
Generating data-flow dependencies from atom. Please wait ...
Exception in thread "main" overflowdb.traversal.filter.StringPropertyFilter$InvalidRegexException: invalid regular expression: ` grpc_core.ChildPolicyHandler.ConfigChangeRequiresNewPolicyInstance:bool(grpc_core::LoadBalancingPolicy::Config *`
	at overflowdb.traversal.filter.StringPropertyFilter$.regexpCompile(StringPropertyFilter.scala:48)
	at overflowdb.traversal.filter.StringPropertyFilter$.regexp(StringPropertyFilter.scala:13)
	at io.shiftleft.codepropertygraph.generated.traversal.CallTraversalExtGen$.typeFullName$extension(Call.scala:597)
	at io.appthreat.x2cpg.passes.taggers.CdxPass.run$$anonfun$1$$anonfun$5$$anonfun$2$$anonfun$5(CdxPass.scala:285)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at io.appthreat.x2cpg.passes.taggers.CdxPass.run$$anonfun$1$$anonfun$5$$anonfun$2(CdxPass.scala:351)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.Vector.foreach(Vector.scala:2124)
	at io.appthreat.x2cpg.passes.taggers.CdxPass.run$$anonfun$1$$anonfun$5(CdxPass.scala:353)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.VectorStatics$.foreachRec(Vector.scala:2124)
	at scala.collection.immutable.Vector.foreach(Vector.scala:2130)
	at io.appthreat.x2cpg.passes.taggers.CdxPass.run$$anonfun$1(CdxPass.scala:354)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1300)
	at io.appthreat.x2cpg.passes.taggers.CdxPass.run(CdxPass.scala:355)
	at io.shiftleft.passes.CpgPass.runOnPart(CpgPass.scala:29)
	at io.shiftleft.passes.NewStyleCpgPassBase.runWithBuilder(CpgPass.scala:134)
	at io.shiftleft.passes.ForkJoinParallelCpgPass.createApplySerializeAndStore(CpgPass.scala:77)
	at io.shiftleft.passes.NewStyleCpgPassBase.createAndApply(CpgPass.scala:124)
	at io.appthreat.atom.Atom$.generateForLanguage(Atom.scala:606)
	at io.appthreat.atom.Atom$.generateAtom(Atom.scala:446)
	at io.appthreat.atom.Atom$.run(Atom.scala:300)
	at io.appthreat.atom.Atom$.run(Atom.scala:294)
	at io.appthreat.atom.Atom$.main(Atom.scala:275)
	at io.appthreat.atom.Atom.main(Atom.scala)
Caused by: java.util.regex.PatternSyntaxException: Unclosed group near index 117
(?s) grpc_core.ChildPolicyHandler.ConfigChangeRequiresNewPolicyInstance:bool(grpc_core::LoadBalancingPolicy::Config *
	at java.base/java.util.regex.Pattern.error(Pattern.java:2204)
	at java.base/java.util.regex.Pattern.accept(Pattern.java:2054)
	at java.base/java.util.regex.Pattern.group0(Pattern.java:3232)
	at java.base/java.util.regex.Pattern.sequence(Pattern.java:2300)
	at java.base/java.util.regex.Pattern.expr(Pattern.java:2245)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1945)
	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1576)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1101)
	at scala.util.matching.Regex.<init>(Regex.scala:234)
	at scala.collection.StringOps$.r$extension(StringOps.scala:852)
	at overflowdb.traversal.filter.StringPropertyFilter$.regexpCompile(StringPropertyFilter.scala:45)
	... 32 more

```

**Comment by almaz045** [comment]
> I've tried to test depscan on https://github.com/grpc/grpc by next command:
> 
> > atom reachables -o app.atom -s reachables.json -l c .
> > p.s. bom.json is exist
> 
> And got next error:
> 
> ```
> Generating data-flow dependencies from atom. Please wait ...
> Exception in thread "main" overflowdb.traversal.filter.StringPropertyFilter$InvalidRegexException: invalid regular expression: ` grpc_core.ChildPolicyHandler.ConfigChangeRequiresNewPolicyInstance:bool(grpc_core::LoadBalancingPolicy::Config *`
> 	at overflowdb.traversal.filter.StringPropertyFilter$.regexpCompile(StringPropertyFilter.scala:48)
> 	at overflowdb.traversal.filter.StringPropertyFilter$.regexp(StringPropertyFilter.scala:13)
> 	at io.shiftleft.codepropertygraph.generated.traversal.CallTraversalExtGen$.typeFullName$extension(Call.scala:597)
> 	at io.appthreat.x2cpg.passes.taggers.CdxPass.run$$anonfun$1$$anonfun$5$$anonfun$2$$anonfun$5(CdxPass.scala:285)
> 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
> 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
> 	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
> 	at io.appthreat.x2cpg.passes.taggers.CdxPass.run$$anonfun$1$$anonfun$5$$anonfun$2(CdxPass.scala:351)
> 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
> 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
> 	at scala.collection.immutable.Vector.foreach(Vector.scala:2124)
> 	at io.appthreat.x2cpg.passes.taggers.CdxPass.run$$anonfun$1$$anonfun$5(CdxPass.scala:353)
> 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
> 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
> 	at scala.collection.immutable.VectorStatics$.foreachRec(Vector.scala:2124)
> 	at scala.collection.immutable.Vector.foreach(Vector.scala:2130)
> 	at io.appthreat.x2cpg.passes.taggers.CdxPass.run$$anonfun$1(CdxPass.scala:354)
> 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
> 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
> 	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
> 	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
> 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1300)
> 	at io.appthreat.x2cpg.passes.taggers.CdxPass.run(CdxPass.scala:355)
> 	at io.shiftleft.passes.CpgPass.runOnPart(CpgPass.scala:29)
> 	at io.shiftleft.passes.NewStyleCpgPassBase.runWithBuilder(CpgPass.scala:134)
> 	at io.shiftleft.passes.ForkJoinParallelCpgPass.createApplySerializeAndStore(CpgPass.scala:77)
> 	at io.shiftleft.passes.NewStyleCpgPassBase.createAndApply(CpgPass.scala:124)
> 	at io.appthreat.atom.Atom$.generateForLanguage(Atom.scala:606)
> 	at io.appthreat.atom.Atom$.generateAtom(Atom.scala:446)
> 	at io.appthreat.atom.Atom$.run(Atom.scala:300)
> 	at io.appthreat.atom.Atom$.run(Atom.scala:294)
> 	at io.appthreat.atom.Atom$.main(Atom.scala:275)
> 	at io.appthreat.atom.Atom.main(Atom.scala)
> Caused by: java.util.regex.PatternSyntaxException: Unclosed group near index 117
> (?s) grpc_core.ChildPolicyHandler.ConfigChangeRequiresNewPolicyInstance:bool(grpc_core::LoadBalancingPolicy::Config *
> 	at java.base/java.util.regex.Pattern.error(Pattern.java:2204)
> 	at java.base/java.util.regex.Pattern.accept(Pattern.java:2054)
> 	at java.base/java.util.regex.Pattern.group0(Pattern.java:3232)
> 	at java.base/java.util.regex.Pattern.sequence(Pattern.java:2300)
> 	at java.base/java.util.regex.Pattern.expr(Pattern.java:2245)
> 	at java.base/java.util.regex.Pattern.compile(Pattern.java:1945)
> 	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1576)
> 	at java.base/java.util.regex.Pattern.compile(Pattern.java:1101)
> 	at scala.util.matching.Regex.<init>(Regex.scala:234)
> 	at scala.collection.StringOps$.r$extension(StringOps.scala:852)
> 	at overflowdb.traversal.filter.StringPropertyFilter$.regexpCompile(StringPropertyFilter.scala:45)
> 	... 32 more
> ```

**Comment by prabhu** [comment]
Interesting test case! There is a type that is confusing the regex during tagging.

**Comment by prabhu** [comment]
@almaz045 could you confirm the version of atom used, since I don't get this error with the latest.

**Comment by prabhu** [comment]
@kittyandrew, could you share the .py file or the code snippet?

**Comment by kittyandrew** [comment]
Hi, I've looked at it again today and realized that I might've included `.venv` directory when pointing to the "current working directory". Problem went away when I pointing only to my source code.

I don't know if that makes sense to debug further

**Comment by prabhu** [comment]
Thank you for confirming. Will keep this issue open in case we face any other problematic pattern in the future.
