### ISSUE TITLE
Tests are failing under java 11

### ISSUE THREAD

**Issue by prabhu** [AppThreat/atom#34]

**Comment by prabhu** [comment]
It turns out eclipse cdt used by c2cpg is forcing a min jdk version > 11

```
java.lang.UnsupportedClassVersionError: org/eclipse/core/runtime/Plugin has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
```
